#!/usr/bin/env bash

USAGE="Usage:\n  c [COMMAND] [ARGS...]\n  c -h|--help\nCommands:\n up \t\t Bring up all containers \n exec \t\t Docker exec into a container \n restart \t Restart a container \n env \t\t Change the environment for docker \n npm \t\t Install npm modules into your container directory \n"

if [ ! -n "$1" ]; then
    printf "Please provide a command. \n${USAGE}"
    exit 1
fi

case "$1" in

up)

    if [ ! -n "$2" ]; then
        dc stop && dc rm --force && dc up -d && dc scale consul=3 app=2
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc up -d $2
    ;;

rebuild)

    if [ ! -n "$2" ]; then
        dc stop && dc rm --force && dc build && dc up -d && dc scale consul=3 app=2
        exit 1
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc stop $CONTAINERNAME && dc rm --force $CONTAINERNAME && dc build $CONTAINERNAME && dc up -d --no-recreate $CONTAINERNAME

    if [ "$CONTAINERNAME" = "app" ]; then
        dc scale app=2
    fi
    ;;

restart)

    if [ ! -n "$2" ]; then
        c down && c up
        exit 0
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc stop $CONTAINERNAME && dc rm --force $CONTAINERNAME && dc up -d --no-recreate $CONTAINERNAME

    if [ "$CONTAINERNAME" = "app" ]; then
        dc scale app=2
    fi
    ;;

scale)

    if [ ! -n "$2" ]; then
        printf "Please provide scaling information. For example: \n c scale app=2 consul=3 \n"
        exit 1
    fi

    dc scale $2

    ;;

down)

    if [ ! -n "$2" ]; then
        dc stop && dc rm --force
        exit 0
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc stop $2 && dc rm --force $2
    ;;

exec)

    if [ ! -n "$2" ]; then
        printf "Please provide a container name. For example: \n  c exec consul [container number, defaults to 1] \n  c exec consul 2 \n"
        exit 1
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    docker exec -it ${COMPOSE_PROJECT_NAME}_${CONTAINERNAME}_${3:-'1'} with-contenv sh
    ;;

env)

    if [ ! -n "$2" ]; then
        printf "Please provide an environment name. \n"
        exit 1
    fi

    if test "$2" = 'reset' -o "$2" = 'RESET'; then
        # Reset dc to load default docker-compose.yml file
        echo COMPOSE_FILE=docker-compose.yml > .env
        printf "You have reset 'dc' to load the default docker-compose.yml file.\n"
        exit 1
    fi

    # Add COMPOSE_FILE environment variable to .env file
    echo COMPOSE_FILE=docker-compose.yml:docker-compose.${2}.yml > .env
    printf "You have configured 'dc' to load from docker-compose.yml and docker-compose.${2}.yml. \nMake sure docker-compose.${2}.yml exists. \n"
    ;;

logs)

    if [ ! -n "$2" ]; then
        dc logs -f
        exit 0
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc logs -f $CONTAINERNAME
    ;;

npm)

    if [ ! -n "$2" ]; then
        printf "Please provide a container name. \n"
        exit 1
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    # Build the NPM command
    COMMANDSTR="npm"

    for i in ${@:3:${#@}}
    do
      COMMANDSTR+=" $i"
    done

    # Create a folder if it doesn't exist for the package.json
    mkdir -p /npm/$CONTAINERNAME
    mkdir -p /npm/$CONTAINERNAME/node_modules

    # Make sure the node_modules directory in the target exists
    mkdir -p ./$CONTAINERNAME/root/app/node_modules

    # Empty the directory if it does exist
    rm -rf /npm/$CONTAINERNAME/node_modules/*

    if [ ! -e ./$CONTAINERNAME/root/app/package.json ]; then
        printf "\nError: Could not find a package.json file in the $CONTAINERNAME/root/app directory.\n\n"
        exit 1
    fi

    # Copy the package.json and node_modules across
    cp -f ./$CONTAINERNAME/root/app/package.json /npm/$CONTAINERNAME
    cp -rf ./$CONTAINERNAME/root/app/node_modules/* /npm/$CONTAINERNAME/node_modules

    # Move into the correct directory.
    cd /npm/$CONTAINERNAME

    # Install the node modules
    eval $COMMANDSTR

    # Move back into the `/vagrant` directory.
    cd /vagrant

    # Remove the current node_modules
    rm -rf ./$CONTAINERNAME/root/app/node_modules/*

    # Copy the newly installed ones across, and the package.json
    cp -fr /npm/$CONTAINERNAME/node_modules/* ./$CONTAINERNAME/root/app/node_modules
    cp -f /npm/$CONTAINERNAME/package.json ./$CONTAINERNAME/root/app

    if [ -e /npm/$CONTAINERNAME/node_modules/.bin ]; then
        mkdir -p ./$CONTAINERNAME/root/app/node_modules/.bin
        cp -fr /npm/$CONTAINERNAME/node_modules/.bin/* ./$CONTAINERNAME/root/app/node_modules/.bin
    fi
    ;;

build)

    if [ ! -n "$2" ]; then
        dc build
        exit 0
    fi

    # remove the trailing / if there is any (this allows user to use tab to complete the container name which corresponding to the directory name)
    CONTAINERNAME=${2%/}

    dc build $CONTAINERNAME
    ;;

ps)

    dc ps
    ;;

-h|--help)

    printf "${USAGE}"
    ;;

*)

    printf "$1 is not supported. \n ${USAGE}"
    ;;

esac
